import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt

data = sio.loadmat('./Materiale/noisyECG.mat')
print(data.keys())

# ecg = data['ecg'].flatten() # change for noisyECG-1.mat
ecg = data['y'].flatten()

fs = 250
# fs = 450 # change for noisyECG-1.mat
t = np.arange(len(ecg)) / fs

from scipy.signal import detrend
import numpy as np

t_idx = np.arange(len(ecg))

# 1. Stima il polinomio di grado 5 che approssima il trend
coeffs = np.polyfit(t_idx, ecg, 5)

# 2. Ricostruisce il trend (valuta il polinomio in ogni punto)
trend = np.polyval(coeffs, t_idx)

# 3. Sottrae il trend dal segnale originale
ecg_detrended = ecg - trend

'''
The logic that we applied here uses the "least squares method" to detrend our signal.
What the method does is using a polynome to find the slower frequencies generated by the movements of the patient, breathing or other similar factors, and then removing them
A polynome approximates a function, at order 5 it is perfect for our purpose
'''

fig, ax = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

ax[0].plot(t, ecg, color='steelblue')
ax[0].set_title('Segnale originale')
ax[0].set_ylabel('Ampiezza')
ax[0].grid(True)

ax[1].plot(t, ecg_detrended, color='green')
ax[1].set_title('Segnale rettificato (detrended)')
ax[1].set_ylabel('Ampiezza')
ax[1].grid(True)

ax[2].plot(t, trend, color='red')
ax[2].set_title('Trend rimosso')
ax[2].set_ylabel('Ampiezza')
ax[2].set_xlabel('Tempo (s)')
ax[2].grid(True)

plt.tight_layout()
plt.show()

from scipy.signal import butter, filtfilt

f_low = 0.5   # Hz - taglia il drift lento (sotto questa freq)
f_high = 25   # Hz - taglia il rumore ad alta freq (sopra questa freq)

# filtro Butterworth di ordine 2
b, a = butter(2, [f_low, f_high], btype='bandpass', fs=fs)

ecg_filtered = filtfilt(b, a, ecg)

# Confronto finale
plt.figure(figsize=(12, 4))
plt.plot(t, ecg_detrended, 'b', label='ECG detrended (polinomio)')
plt.plot(t, ecg_filtered, 'r', label='ECG filtrato (Butterworth)')
plt.xlabel('Tempo (s)')
plt.ylabel('Ampiezza')
plt.legend()
plt.grid(True)
plt.show()

from scipy.signal import find_peaks

distance_min = int(0.4 * fs)  # = 180 campioni
peaks, _ = find_peaks(ecg_filtered, prominence=150, distance=distance_min)
"""
note: We are working on raw data directly from the ADC.
We would need the machine's hw paramethers to normalyze the results, but unfortunately the dataset doesn't provide them.
Normally we would simply do "prominence = 0.9", but in our case we have to adapt the parameters manually to obtain the peaks
"""

rr_campioni = np.mean(np.diff(peaks))
rr_secondi = rr_campioni / fs
heart_rate = 60 / rr_secondi

print(f"Picchi R trovati: {len(peaks)}")
print(f"Intervallo R-R medio: {rr_secondi:.3f} s")
print(f"Frequenza cardiaca: {round(heart_rate)} bpm")

plt.figure(figsize=(12, 4))
plt.plot(t, ecg_filtered, 'r', label='ECG filtrato')
plt.plot(t[peaks], ecg_filtered[peaks], '^',
         color='blue', markersize=8, label='Picchi R')
plt.title(f'Picchi R rilevati: {len(peaks)}')
plt.xlabel('Tempo (s)')
plt.ylabel('Ampiezza')
plt.legend()
plt.grid(True)
plt.show()